<?php

namespace App\Services;

class LogReaderService
{

    /**
     * @brief Retrieves filtered log entries with cursor-based pagination support.
     *
     * @details
     * This method allows you to read log files generated by Laravel and retrieve
     * entries filtered by severity level.
     *
     * The file is read from the end to the beginning to prioritize
     * the most recent events and optimize performance when dealing with
     * large files.
     *
     * Additionally, it implements cursor-based pagination, allowing reading to continue
     * from a specific line in the file without needing to reprocess records
     * previously queried.
     *
     * Main flow:
     * - Validates the existence of the log file.
     * - Applies default log levels when none are provided.
     * - Positions the read cursor.
     * - Scans the file in reverse order.
     * - Filters lines before decoding JSON to optimize performance.
     * - Returns paginated results along with the next available cursor position.
     *
     * @param array $levels List of allowed log levels.
     *                      If not specified, the following levels are used:
     *                      ERROR, INFO, WARNING, CRITICAL, ALERT, and EMERGENCY.
     *
     * @param string $date Date associated with the log file.
     *                     Expected format: `YYYY-MM-DD`.
     *
     * @param string|null $cursor Encoded cursor used to continue reading
     *                            from a specific position in the file.
     * 
     *
     * @param int $limit Maximum number of records to return.
     *                   Default value: `100`.
     *
     * @return array
     * Returns an array containing:
     * - `status`     : Operation status.
     * - `statusCode` : HTTP status code.
     * - `message`    : Descriptive message.
     * - `data`       : Found logs and pagination data.
     *
     * @note
     * Each line of the file must contain a valid, independent JSON object.
     *
     * @warning
     * Invalid cursors, nonexistent files, or corrupted lines
     * may result in partial responses or controlled errors.
     */
    public static function getLogs(
        array $levels = [],
        string $date = '',
        ?string $cursor = null,
        int $limit = 100
    ): array {

        $response = [
            'status' => true,
            'statusCode' => 200,
            'message' => 'success',
            'data' => []
        ];

        try {

            //Builds the path to the log file corresponding to the requested date.
            $path = storage_path("logs/laravel-{$date}.log");

            if (file_exists($path)) {
                // Applies default log levels when logs are not sent.
                $levels = $levels ??
                    [
                        'ERROR',
                        'INFO',
                        'WARNING',
                        'CRITICAL',
                        'ALERT',
                        'EMERGENCY'
                    ];

                //Open the file in read-only mode using SplFileObject to optimize the handling of large files.
                $file = new \SplFileObject($path, 'r');

                // Move the cursor to the last line of the file
                $file->seek(PHP_INT_MAX);

                // Gets the index of the last available line
                $currentLine = $lastLine = $file->key();

                // Check whether it is valid to continue reading
                $availableReadLogs = true;

                // Validate and decode the received cursor
                if (!empty($cursor)) {

                    $responseDecodedCursor = self::decodedCursor($cursor, $path);

                    if ($responseDecodedCursor['status']) {
                        // Retrieves the line where reading will resume
                        $currentLine = (int) $responseDecodedCursor['data']['line'];
                    } else {
                        // Invalid or tampered cursor
                        $availableReadLogs = false;
                        $response['status'] = false;
                        $response['statusCode'] = $responseDecodedCursor['statusCode'];
                        $response['message'] = $responseDecodedCursor['message'];
                    }
                }

                if ($availableReadLogs) {
                    // Ensures that the cursor line remains within the valid boundaries of the file.
                    if ($currentLine > $lastLine) {
                        $currentLine = $lastLine;
                    }

                    if ($currentLine < 0) {
                        $currentLine = 0;
                    }

                    //Iterate through the file from the end to the beginning to retrieve the most recent logs first.
                    $count = 0;

                    for ($lineNumber = $currentLine; $lineNumber >= 0; $lineNumber--) {

                        // Move the cursor to the current line
                        $file->seek($lineNumber);

                        // Remove spaces and line breaks
                        $line = trim($file->current());

                        //Skip empty lines
                        if (empty($line)) {
                            continue;
                        }

                        //Optimizes performance by avoiding JSON decoding when the line does not contain valid levels.
                        $containsLevel = false;

                        $containsLevel = !empty(array_filter($levels, function ($level) use ($line) {
                            return str_contains($line, "\"{$level}\"");
                        }));

                        // Skip lines that do not contain valid levels
                        if (!$containsLevel) {
                            continue;
                        }

                        //Convert the current line to an associative array.
                        $decoded = json_decode($line, true);

                        // Ignore invalid lines or corrupted JSON
                        if (!$decoded || !is_array($decoded)) {
                            continue;
                        }

                        //Verify that the log level matches exactly the allowed levels.
                        if (isset($decoded['level_name']) && in_array(strtoupper($decoded['level_name']), $levels)) {
                            // Add the valid record to the response
                            $response['data']['logs'][] = $decoded;
                            $count++;
                        }

                        //Generate the pagination cursor when the maximum limit is reached.
                        if ($count >= $limit) {

                            $encodedCursor = self::encodedCursor($lineNumber, $path, $date, $limit);

                            if ($encodedCursor['status']) {
                                $response['data']['pagination'] = $encodedCursor['data'];
                            } else {
                                $response = $encodedCursor;
                            }

                            break;
                        }
                    }
                }
            } else {
                $response['status'] = false;
                $response['statusCode'] = 404;
                $response['message'] = 'Log file not found.';
            }
        } catch (\Throwable $th) {

            $response = [
                'status' => false,
                'statusCode' => 500,
                'message' => $th->getMessage(),
                'data' => []
            ];
        }

        return $response;
    }

    /**
     * @brief Decodes and validates a pagination cursor for reading logs.
     *
     * @details
     * This method receives a Base64-encoded cursor containing the information
     * needed to continue reading a log file in paginated mode.
     *
     * The cursor must contain a valid JSON structure with:
     * - `line`: the line number from which reading will resume.
     * - `file` : name of the file associated with the cursor.
     *
     * The method validates:
     * - That the cursor can be decoded correctly.
     * - That the cursor structure is valid.
     * - That the cursor belongs to the currently requested file.
     *
     * If validation is successful, it returns the decoded line number.
     *
     * @param string $cursor Base64-encoded cursor with pagination information.
     *
     * @param string $pathFile Full path of the current log file.
     *                         Used to validate that the cursor belongs
     *                         to the correct file.
     *
     * @return array
     * Returns an array containing:
     * - `status`     : Operation status.
     * - `statusCode` : Representative HTTP status code.
     * - `message`    : Descriptive message.
     * - `data`       : Decoded cursor information.
     *
     * @note
     * The cursor must contain valid JSON serialized and Base64-encoded.
     *
     * @warning
     * If the cursor has been tampered with, belongs to another file,
     * or has an invalid structure, a controlled error will be returned.
     */
    private static function decodedCursor(string $cursor, string $pathFile): array
    {

        $responseDecodedCursor = [
            'status' => true,
            'statusCode' => 200,
            'message' => 'success',
            'data' => []
        ];

        try {

            /**
             * Decode the cursor:
             * 1. Base64 decode
             * 2. Convert JSON to an associative array
             */
            $decodedCursor = json_decode(
                base64_decode($cursor),
                true,
                512,
                JSON_THROW_ON_ERROR
            );

            //Verifies that the line exists and is a number
            if (isset($decodedCursor['line']) && is_numeric($decodedCursor['line'])) {
                //Verify that the cursor belongs to the same requested file.
                if (isset($decodedCursor['file']) && $decodedCursor['file'] !== basename($pathFile)) {

                    return [
                        'status' => false,
                        'statusCode' => 422,
                        'message' => 'Cursor does not belong to this file.',
                        'data' => []
                    ];
                }
                // Assigns the validated line converted to an integer
                $responseDecodedCursor['data']['line'] = (int) $decodedCursor['line'];
            } else {
                $responseDecodedCursor = [
                    'status' => false,
                    'statusCode' => 422,
                    'message' => 'Invalid cursor structure.',
                    'data' => []
                ];
            }
        } catch (\Throwable $th) {
            $responseDecodedCursor['status'] = false;
            $responseDecodedCursor['statusCode'] = 500;
            $responseDecodedCursor['message'] = $th->getMessage();
        }

        return $responseDecodedCursor;
    }

    /**
     * @brief Generates a pagination cursor for incremental log reading.
     *
     * @details
     * This method constructs a Base64-encoded cursor containing
     * the information needed to continue paginated reading of a
     * log file starting from a specific line.
     *
     * The cursor includes:
     * - The next line number to be processed.
     * - Name of the associated file.
     * - Date of the queried log.
     *
     * The information is serialized in JSON format and subsequently
     * Base64-encoded to facilitate transport and reuse.
     *
     * Additionally, the method returns pagination metadata indicating:
     * - Requested record limit.
     * - Whether more results are available.
     * - Reading order applied.
     *
     * @param int $lineNumber Current line number processed in the file.
     *
     * @param string $pathFile Full path to the log file.
     *                         Used to associate the cursor with the correct file.
     *
     * @param string $date Date associated with the log file.
     *                     Expected format: `YYYY-MM-DD`.
     *
     * @param int $limit Maximum number of records processed per page.
     *
     * @return array
     * Returns an array containing:
     * - `status`     : Operation status.
     * - `statusCode` : Representative HTTP code.
     * - `message`    : Descriptive message.
     * - `data`       : Paging information and generated cursor.
     * 
     *
     * @note
     * The generated cursor can be reused later
     * to continue reading the file from the current position.
     *
     * @warning
     * If the file changes between requests (rotation or modification),
     * the generated cursor may no longer be valid.
     */
    private static function encodedCursor(int $lineNumber, string $pathFile, string $date, int $limit): array
    {

        $responseEncoded = [
            'status' => true,
            'statusCode' => 200,
            'message' => 'Success',
            'data' => []
        ];

        try {

            // Calculate the next available line to continue reading
            $nextLine = $lineNumber - 1;

            //The cursor is generated only if there are more lines available to process.
            $nextCursor = null;

            if ($nextLine >= 0) {

                // Information to be serialized within the cursor
                $nextCursorPayload = [
                    'line' => $nextLine,
                    'file' => basename($pathFile),
                    'date' => $date,
                ];

                /**
                 * Encodes the payload:
                 * 1. Convert to JSON
                 * 2. Base64 encoding
                 */
                $nextCursor = base64_encode(
                    json_encode($nextCursorPayload)
                );
            }

            // Build the pagination response
            $responseEncoded['data'] = [
                'limit' => $limit,
                'next_cursor' => $nextCursor, //Cursor to retrieve the next page
                'has_more' => $nextLine >= 0,  // Indicates whether there are more records available
                'order' => 'desc' // Reading order applied to the file
            ];
        } catch (\Throwable $th) {
            $responseEncoded['status'] = false;
            $responseEncoded['statusCode'] = 500;
            $responseEncoded['message'] = $th->getMessage();
        }

        return $responseEncoded;
    }
}
